"""
Defines a attributes set to be considered in the generation data process.
"""
ATRIBUTOS = {'NACIONALIDAD': {'NAME': 'Nacionalidad',
                              'QUESTION': 'Indica tu nacionalidad',
                              'VALUES': ['Española', 'Comunitaria', 'No comunitario', 'Apátrida'],
                              'HELPERS': ['', 'Ciudadano de la Unión Europea que ostenta la nacionalidad de cualquiera de los Estados miembros de la UE', '',
                                          'Persona que no tiene nacionalidad de ningún país'],
                              'TYPE': list,
                              'HELP': '',
                              'DEPENDENCIES': []},
             'RESIDENCIA': {'NAME': 'Residencia efectiva (*un año inmediatamente anterior a la presentación de la solicitud*)',
                            'QUESTION': 'Indica tu residencia efectiva',
                            'VALUES': ['España', 'Madrid'],
                            'HELPERS': None,
                            'TYPE': list,
                            'HELP': 'La residencia efectiva es en la que se ha estado viviendo durante el año inmediatamente anterior a la presentación de la solicitud.',
                            'DEPENDENCIES': []},
             'MADRID': {'NAME': 'Empadronamiento en municipio de la Comunidad de Madrid',
                        'QUESTION': '¿Estás empadronado en un municipio de la Comunidad de Madrid?',
                        'VALUES': ['Sí', 'No'],
                        'HELPERS': None,
                        'TYPE': bool,
                        'HELP': '',
                        'DEPENDENCIES': []},

             'EDAD': {'NAME': 'Edad',
                      'QUESTION': 'Indica tu edad',
                      'VALUES': ['<3', '>18', '>21', '>30', '<30', '>65', '<65'],
                      'HELPERS': None,
                      'TYPE': list,
                      'HELP': '',
                      'DEPENDENCIES': []},

             'EMANCIPADO': {'NAME': 'Emancipado',
                            'QUESTION': '¿Estás emancipado?',
                            'VALUES': ['Sí', 'No'],
                            'HELPERS': None,
                            'TYPE': bool,
                            'HELP': 'Si es menor de edad pero se ha independizado.',
                            'DEPENDENCIES': [('EDAD', '=', '<18')]},

             'UNIDAD': {'NAME': 'Unidad de convivencia',
                        'QUESTION': 'Indica si formas parte de alguna de estas unidades de convivencia',
                        'VALUES': ['Unión matromonial', 'Unión de hecho', 'Consanguiniedad (hasta 4º grado)', 'Afinidad (hasta 2º grado)', 'Tutela', 'Discapacitados a su cargo',
                                   'Acogimiento familiar', 'No'],
                        'HELPERS': ['',
                                    'La pareja de hecho es la unión de dos personas, indistintamente del sexo, que tienen una relación estable de afectividad, que no han contraido matrimonio y conviven en la misma vivienda, sin ser necesario que haya hijos en común.',
                                    'Parentesco natural de una persona con otra u otras que descienden de los mismos antepasados.',
                                    'Es un tipo de parentesco que se produce por un vínculo legal a través del matrimonio u otro tipo de unión civil.',
                                    'Es una institución jurídica cuyo objeto es la guarda de la persona y sus bienes, o solamente de los bienes o de la persona, de quien, no estando bajo la patria potestad, es incapaz de gobernarse por sí mismo por ser menor de edad o estar declarado como incapacitado.',
                                    '',
                                    'Es una medida de protección de la infancia de carácter temporal o permanente, mediante la cual se ofrece un entorno familiar adecuado a los menores que, por distintas circunstancias, han pasado a ser tutelados por la administración correspondiente, hasta su mayoría edad, o puedan volver con sus familias biológicas o mientras se formaliza el proceso de adopción.',
                                    'Ninguna de las anteriores'],
                        'TYPE': list,
                        'HELP': 'La unidad de convivencia está formada por todas las personas que vivan en el mismo domicilio, unidas por vínculo matrimonial o que se hayan constituido como pareja '
                                'de hecho, y sus familiares hasta el segundo grado por consanguinidad afinidad o adopción u otras personas con las que conviva en virtud de guarda con fines de '
                                'adopción o acogimiento familiar permanente.',
                        'DEPENDENCIES': []},

             'VULNERABILIDAD_ECO': {'NAME': 'Vulnerabilidad Económica',
                                    'QUESTION': 'Indica tus condiciones económicas',
                                    'VALUES': ['No', 'Paro', '<70% Salario Mínimo Anual', 'Renta per cápita familiar <10.000', 'Sin renta', 'Sin ingresos', 'Sin patrimonio'],
                                    'HELPERS': ['No se encuentra en vulnerabilidad económica',
                                                'Se considera que se encuentran en “el paro”, aquellas personas que estén recibiendo la prestación contributiva del Estado que protege la situación de desempleo de quienes pudiendo y queriendo trabajar, pierdan su empleo de forma temporal o definitiva o vean reducida temporalmente su jornada ordinaria de trabajo entre un mínimo de un 10 % y un 70 %.',
                                                '',
                                                '',
                                                'Ingreso fruto del rendimiento laboral. Se considerará que la persona solicitante no tiene renta suficiente, teniendo en cuenta todas aquellas rentas anuales computables de la persona beneficiaria individual o del conjunto de miembros de la unidad de convivencia, cuando el promedio mensual sea inferior, al menos en 10 euros, a la cuantía mensual de la renta garantizada con esta prestación.',
                                                'No computarán como ingresos los salarios sociales, rentas mínimas de inserción o ayudas análogas de asistencia social concedidas por las comunidades autónomas, y otros ingresos y rentas de acuerdo con lo previsto en el artículo 18.',
                                                'Se considera que la persona beneficiaria individual ostenta patrimonio suficiente cuando sea titular de un patrimonio valorado en un importe igual o superior a tres veces la cuantía correspondiente de renta garantizada por el ingreso mínimo vital para una persona beneficiaria individual.'],
                                    'TYPE': list,
                                    'HELP': 'Alguien se encuentra en situación de vulnerabilidad económica cuando esta en Desempleo, Incluido en un ERTE (Expediente de regulación de empleo), '
                                            'Reducción de jornada, Cualquier situación similar que suponga una "pérdida sustancial de ingresos” en la unidad de convivencia.',
                                    'DEPENDENCIES': [('EDAD', '=', '>18')]},

             'VIOLENCIA': {'NAME': 'Violencia de género',
                           'QUESTION': '¿Eres víctima de violencia de genero?',
                           'VALUES': ['Sí', 'No'],
                           'HELPERS': None,
                           'TYPE': bool,
                           'HELP': '',
                           'DEPENDENCIES': []},

             'TRATA': {'NAME': 'Trata de seres humanos',
                       'QUESTION': '¿Eres víctima de trata de seres humanos?',
                       'VALUES': ['Sí', 'No'],
                       'HELPERS': None,
                       'TYPE': bool,
                       'HELP': '',
                       'DEPENDENCIES': []},

             'EXPLOTACION': {'NAME': 'Explotación sexual',
                             'QUESTION': '¿Eres víctima de explotación sexual?',
                             'VALUES': ['Sí', 'No'],
                             'HELPERS': None,
                             'TYPE': bool,
                             'HELP': '',
                             'DEPENDENCIES': []},

             'MENORES': {'NAME': 'Menores escolarizados o discapacitados a cargo',
                         'QUESTION': '¿Tienes menores escolarizados o discapacitados a cargo?',
                         'VALUES': ['Sí', 'No'],
                         'HELPERS': None,
                         'TYPE': bool,
                         'HELP': '',
                         'DEPENDENCIES': [('EDAD', '=', '>18')]},

             'PARADOS_LARGA_DURACION': {'NAME': 'Desempleados de larga duración',
                                        'QUESTION': '¿Eres desempleado de larga duración?',
                                        'VALUES': ['Sí', 'No'],
                                        'HELPERS': None,
                                        'TYPE': bool,
                                        'HELP': '',
                                        'DEPENDENCIES': [('EDAD', '=', '>21')]},

             'DISCAPACIDAD': {'NAME': 'Grado de discapacidad',
                              'QUESTION': 'Indica tu grado de discapacidad',
                              'VALUES': ['No', '>=33%', '>=75%', '>=85%'],
                              'HELPERS': None,
                              'TYPE': list,
                              'HELP': '',
                              'DEPENDENCIES': []},

             'SOLICITUD_PREVIA': {'NAME': 'Solicitud previa de otras prestaciones o pensiones',
                                  'QUESTION': '¿Has solicitado otras prestaciones o pensiones?',
                                  'VALUES': ['Sí', 'No'],
                                  'HELPERS': None,
                                  'TYPE': bool,
                                  'HELP': '',
                                  'DEPENDENCIES': []},

             'INSERCION': {'NAME': 'Programa individual de inserción',
                           'QUESTION': '¿Tienes un programa individual de inserción?',
                           'VALUES': ['Sí', 'No'],
                           'HELPERS': None,
                           'TYPE': bool,
                           'HELP': '',
                           'DEPENDENCIES': []},

             'RIESGOS': {'NAME': 'Riesgo de empeoramiento de no aplicarse los tratamientos correspondientes',
                         'QUESTION': '¿Hay riesgo de empeoramiento de no aplicarse los tratamientos correspondientes?',
                         'VALUES': ['Sí', 'No'],
                         'HELPERS': None,
                         'TYPE': bool,
                         'HELP': '',
                         'DEPENDENCIES': []},

             'RECUPERACION': {'NAME': 'Posibilidad de recuperación',
                              'QUESTION': '¿Hay posibilidades de recuperación?',
                              'VALUES': ['Sí', 'No'],
                              'HELPERS': None,
                              'TYPE': bool,
                              'HELP': '',
                              'DEPENDENCIES': []},

             'CURSANDO_ESTUDIOS': {'NAME': 'Estudios en curso',
                                   'QUESTION': '¿Estás cursando estudios?',
                                   'VALUES': ['Sí', 'No'],
                                   'HELPERS': None,
                                   'TYPE': bool,
                                   'HELP': '',
                                   'DEPENDENCIES': []},

             'MODALIDAD_ESTUDIOS': {'NAME': 'Modalidad presencial',
                                    'QUESTION': '¿La formación es presencial?',
                                    'VALUES': ['Sí', 'No'],
                                    'HELPERS': None,
                                    'TYPE': bool,
                                    'HELP': '',
                                    'DEPENDENCIES': [('CURSANDO_ESTUDIOS', '=', 'Sí')]},

             'ESTUDIOS': {'NAME': 'Estudios en curso',
                          'QUESTION': 'Indica los estudios en curso',
                          'VALUES': ['No', 'Infantil', 'Primaria', 'Secundaria', 'Bachillerato', 'Formación Profesional'],
                          'HELPERS': None,
                          'TYPE': list,
                          'HELP': '',
                          'DEPENDENCIES': [('CURSANDO_ESTUDIOS', '=', 'Sí')]},

             'CENTRO_ESTUDIOS': {'NAME': 'Centro Privado',
                                 'QUESTION': '¿El centro de estudios es privado?',
                                 'VALUES': ['Sí', 'No'],
                                 'HELPERS': None,
                                 'TYPE': bool,
                                 'HELP': '',
                                 'DEPENDENCIES': [('CURSANDO_ESTUDIOS', '=', 'Sí')]},

             'LUGAR_ESTUDIOS': {'NAME': 'Centro situado en la Comunidad de Madrid',
                                'QUESTION': '¿El centro de estudios está situado en la Comunidad de Madrid?',
                                'VALUES': ['Sí', 'No'],
                                'HELPERS': None,
                                'TYPE': bool,
                                'HELP': '',
                                'DEPENDENCIES': [('CURSANDO_ESTUDIOS', '=', 'Sí')]},

             'IDIOMA_ESTUDIOS': {'NAME': 'Estudios bilingües',
                                 'QUESTION': '¿Los estudios son bilingües?',
                                 'VALUES': ['Sí', 'No'],
                                 'HELPERS': None,
                                 'TYPE': bool,
                                 'HELP': '',
                                 'DEPENDENCIES': [('CURSANDO_ESTUDIOS', '=', 'Sí')]},

             'REPETIDOR': {'NAME': 'Repetidor',
                           'QUESTION': '¿Eres repetidor?',
                           'VALUES': ['Sí', 'No'],
                           'HELPERS': None,
                           'TYPE': bool,
                           'HELP': '',
                           'DEPENDENCIES': [('CURSANDO_ESTUDIOS', '=', 'Sí')]},

             'EDUCACION_ESPECIAL': {'NAME': 'Necesidades especiales',
                                    'QUESTION': '¿Tiene necesidades educativas especiales?',
                                    'VALUES': ['Sí', 'No'],
                                    'HELPERS': None,
                                    'TYPE': bool,
                                    'HELP': '',
                                    'DEPENDENCIES': [('CURSANDO_ESTUDIOS', '=', 'Sí')]},

             'COTIZACION': {'NAME': 'Periodo mínimo',
                            'QUESTION': '¿Has cotizado el periodo mínimo?',
                            'VALUES': ['Sí', 'No'],
                            'HELPERS': None,
                            'TYPE': bool,
                            'HELP': '',
                            'DEPENDENCIES': [('EDAD', '=', '>30')]},

             'PERIODO_MINIMO_ALTA': {'NAME': 'Periodo mínimo de cotización dado de alta',
                                     'QUESTION': 'Indica tu periodo mínimo de cotización dado de alta',
                                     'VALUES': ['No', '15 años o más', '1800 días o más', '500 días (periodo ininterrumpido durante 5 años)', '365 días (6 años inmediantamente anteriores)'],
                                     'HELPERS': None,
                                     'TYPE': list,
                                     'HELP': '',
                                     'DEPENDENCIES': [('EDAD', '=', '>18')]},

             'PERIODO_MINIMO_NO_ALTA': {'NAME': 'Periodo mínimo de cotización no dado de alta',
                                        'QUESTION': '¿Has cotizado más de 15 años aunque ahora no estés dado de alta?',
                                        'VALUES': ['Sí', 'No'],
                                        'HELPERS': None,
                                        'TYPE': list,
                                        'HELP': '',
                                        'DEPENDENCIES': [('EDAD', '=', '>30')]},

             'FALLECIMIENTO_CONYUGE': {'NAME': 'Fallecimiento por accidente del cónyuge',
                                       'QUESTION': '¿Ha fallecido por accidente el cónyuge?',
                                       'VALUES': ['Sí', 'No'],
                                       'HELPERS': None,
                                       'TYPE': list,
                                       'HELP': '',
                                       'DEPENDENCIES': [('EDAD', '=', '>18')]},

             'TEMORES': {'NAME': 'Temores fundados de persecución (*con la existencia de uno de ellos es suficente*)',
                         'QUESTION': 'Indica si hay temores fundados de persecución',
                         'VALUES': ['No', 'Raza', 'Religión', 'Nacionalidad', 'Opiniones Políticas', 'Pertenencia a un grupo social', 'Género', 'Orientación sexual'],
                         'HELPERS': None,
                         'TYPE': list,
                         'HELP': '',
                         'DEPENDENCIES': []}
             }
