ATRIBUTOS = {'NACIONALIDAD': {'NAME': 'Nacionalidad',
                              'QUESTION': 'Indica tu nacionalidad',
                              'VALUES': ['Española', 'Comunitaria', 'No comunitario', 'Apátrida'],
                              'HELPERS': ['', 'Ciudadano de la Unión Europea que ostenta la nacionalidad de cualquiera de los Estados miembros de la UE', '',
                                          'Persona que no tiene nacionalidad de ningún país'],
                              'TYPE': list,
                              'HELP': ''},
             'RESIDENCIA': {'NAME': 'Residencia efectiva (*un año inmediatamente anterior a la presentación de la solicitud*)',
                            'QUESTION': 'Indica tu residencia efectiva',
                            'VALUES': ['España', 'Madrid'],
                            'HELPERS': None,
                            'TYPE': list,
                            'HELP': 'La residencia efectiva es en la que se ha estado viviendo durante el año inmediatamente anterior a la presentación de la solicitud.'},
             'MADRID': {'NAME': 'Empadronamiento en municipio de la Comunidad de Madrid',
                        'QUESTION': '¿Estás empadronado en un municipio de la Comunidad de Madrid?',
                        'VALUES': ['Sí', 'No'],
                        'HELPERS': None,
                        'TYPE': bool,
                        'HELP': ''},

             'EDAD': {'NAME': 'Edad',
                      'QUESTION': 'Indica tu edad',
                      'VALUES': None,
                      'HELPERS': None,
                      'TYPE': float,
                      'HELP': ''},

             'EMANCIPADO': {'NAME': 'Emancipado',
                            'QUESTION': '¿Estás emancipado?',
                            'VALUES': ['Sí', 'No'],
                            'HELPERS': None,
                            'TYPE': bool,
                            'HELP': 'Si es menor de edad pero se ha independizado.'},

             'UNIDAD': {'NAME': 'Unidad de convivencia',
                        'QUESTION': 'Indica si formas parte de alguna de estas unidades de convivencia',
                        'VALUES': ['Unión matromonial', 'Unión de hecho', 'Consanguiniedad (hasta 4º grado)', 'Afinidad (hasta 2º grado)', 'Tutela', 'Discapacitados a su cargo',
                                   'Acogimiento familiar', 'No'],
                        'HELPERS': ['',
                                    'La pareja de hecho es la unión de dos personas, indistintamente del sexo, que tienen una relación estable de afectividad, que no han contraido matrimonio y conviven en la misma vivienda, sin ser necesario que haya hijos en común.',
                                    'Parentesco natural de una persona con otra u otras que descienden de los mismos antepasados.',
                                    'Es un tipo de parentesco que se produce por un vínculo legal a través del matrimonio u otro tipo de unión civil.',
                                    'Es una institución jurídica cuyo objeto es la guarda de la persona y sus bienes, o solamente de los bienes o de la persona, de quien, no estando bajo la patria potestad, es incapaz de gobernarse por sí mismo por ser menor de edad o estar declarado como incapacitado.',
                                    '',
                                    'Es una medida de protección de la infancia de carácter temporal o permanente, mediante la cual se ofrece un entorno familiar adecuado a los menores que, por distintas circunstancias, han pasado a ser tutelados por la administración correspondiente, hasta su mayoría edad, o puedan volver con sus familias biológicas o mientras se formaliza el proceso de adopción.',
                                    'Ninguna de las anteriores'],
                        'TYPE': list,
                        'HELP': 'La unidad de convivencia está formada por todas las personas que vivan en el mismo domicilio, unidas por vínculo matrimonial o que se hayan constituido como pareja '
                                'de hecho, y sus familiares hasta el segundo grado por consanguinidad afinidad o adopción u otras personas con las que conviva en virtud de guarda con fines de '
                                'adopción o acogimiento familiar permanente.'},

             'VULNERABILIDAD_ECO': {'NAME': 'Vulnerabilidad Económica',
                                    'QUESTION': 'Indica tus condiciones económicas',
                                    'VALUES': ['No', 'Paro', '<70% Salario Mínimo Anual', 'Renta per cápita familiar <10.000', 'Sin renta', 'Sin ingresos', 'Sin patrimonio'],
                                    'HELPERS': ['No se encuentra en vulnerabilidad económica',
                                                'Se considera que se encuentran en “el paro”, aquellas personas que estén recibiendo la prestación contributiva del Estado que protege la situación de desempleo de quienes pudiendo y queriendo trabajar, pierdan su empleo de forma temporal o definitiva o vean reducida temporalmente su jornada ordinaria de trabajo entre un mínimo de un 10 % y un 70 %.',
                                                '',
                                                '',
                                                'Ingreso fruto del rendimiento laboral. Se considerará que la persona solicitante no tiene renta suficiente, teniendo en cuenta todas aquellas rentas anuales computables de la persona beneficiaria individual o del conjunto de miembros de la unidad de convivencia, cuando el promedio mensual sea inferior, al menos en 10 euros, a la cuantía mensual de la renta garantizada con esta prestación.',
                                                'No computarán como ingresos los salarios sociales, rentas mínimas de inserción o ayudas análogas de asistencia social concedidas por las comunidades autónomas, y otros ingresos y rentas de acuerdo con lo previsto en el artículo 18.',
                                                'Se considera que la persona beneficiaria individual ostenta patrimonio suficiente cuando sea titular de un patrimonio valorado en un importe igual o superior a tres veces la cuantía correspondiente de renta garantizada por el ingreso mínimo vital para una persona beneficiaria individual.'],
                                    'TYPE': list,
                                    'HELP': 'Alguien se encuentra en situación de vulnerabilidad económica cuando esta en Desempleo, Incluido en un ERTE (Expediente de regulación de empleo), '
                                            'Reducción de jornada, Cualquier situación similar que suponga una "pérdida sustancial de ingresos” en la unidad de convivencia.'},

             'VIOLENCIA': {'NAME': 'Violencia de género',
                           'QUESTION': '¿Eres víctima de violencia de genero?',
                           'VALUES': ['Sí', 'No'],
                           'HELPERS': None,
                           'TYPE': bool,
                           'HELP': ''},

             'TRATA': {'NAME': 'Trata de seres humanos',
                       'QUESTION': '¿Eres víctima de trata de seres humanos?',
                       'VALUES': ['Sí', 'No'],
                       'HELPERS': None,
                       'TYPE': bool,
                       'HELP': ''},

             'EXPLOTACIOM': {'NAME': 'Explotación sexual',
                             'QUESTION': '¿Eres víctima de explotación sexual?',
                             'VALUES': ['Sí', 'No'],
                             'HELPERS': None,
                             'TYPE': bool,
                             'HELP': ''},

             'MENORES': {'NAME': 'Menores escolarizados o discapacitados a cargo',
                         'QUESTION': '¿Tienes menores escolarizados o discapacitados a cargo?',
                         'VALUES': ['Sí', 'No'],
                         'HELPERS': None,
                         'TYPE': bool,
                         'HELP': ''},

             'PARADOS_LARGA_DURACION': {'NAME': 'Desempleados de larga duración',
                                        'QUESTION': '¿Eres desempleado de larga duración?',
                                        'VALUES': ['Sí', 'No'],
                                        'HELPERS': None,
                                        'TYPE': bool,
                                        'HELP': ''},

             'DISCAPACIDAD': {'NAME': 'Grado de discapacidad',
                              'QUESTION': 'Indica tu grado de discapacidad',
                              'VALUES': ['No', '>=33%', '>=75%', '>=85%'],
                              'HELPERS': None,
                              'TYPE': list,
                              'HELP': ''},

             'SOLICITUD_PREVIA': {'NAME': 'Solicitud previa de otras prestaciones o pensiones',
                                  'QUESTION': '¿Has solicitado otras prestaciones o pensiones?',
                                  'VALUES': ['Sí', 'No'],
                                  'HELPERS': None,
                                  'TYPE': bool,
                                  'HELP': ''},

             'INSERCION': {'NAME': 'Programa individual de inserción',
                           'QUESTION': '¿Tienes un programa individual de inserción?',
                           'VALUES': ['Sí', 'No'],
                           'HELPERS': None,
                           'TYPE': bool,
                           'HELP': ''},

             'RIESGOS': {'NAME': 'Riesgo de empeoramiento de no aplicarse los tratamientos correspondientes',
                         'QUESTION': '¿Hay riesgo de empeoramiento de no aplicarse los tratamientos correspondientes?',
                         'VALUES': ['Sí', 'No'],
                         'HELPERS': None,
                         'TYPE': bool,
                         'HELP': ''},

             'RECUPERACION': {'NAME': 'Posibilidad de recuperación',
                              'QUESTION': '¿Hay posibilidades de recuperación?',
                              'VALUES': ['Sí', 'No'],
                              'HELPERS': None,
                              'TYPE': bool,
                              'HELP': ''},

             'CURSANDO_ESTUDIOS': {'NAME': 'Estudios en curso',
                                   'QUESTION': '¿Estás cursando estudios?',
                                   'VALUES': ['Sí', 'No'],
                                   'HELPERS': None,
                                   'TYPE': bool,
                                   'HELP': ''},

             'MODALIDAD_ESTUDIOS': {'NAME': 'Modalidad presencial',
                                    'QUESTION': '¿La formación es presencial?',
                                    'VALUES': ['Sí', 'No'],
                                    'HELPERS': None,
                                    'TYPE': bool,
                                    'HELP': ''},

             'ESTUDIOS': {'NAME': 'Estudios en curso',
                          'QUESTION': 'Indica los estudios en curso',
                          'VALUES': ['No', 'Infantil', 'Primaria', 'Secundaria', 'Bachillerato', 'Formación Profesional'],
                          'HELPERS': None,
                          'TYPE': list,
                          'HELP': ''},

             'CENTRO_ESTUDIOS': {'NAME': 'Centro Privado',
                                 'QUESTION': '¿El centro de estudios es privado?',
                                 'VALUES': ['Sí', 'No'],
                                 'HELPERS': None,
                                 'TYPE': bool,
                                 'HELP': ''},

             'LUGAR_ESTUDIOS': {'NAME': 'Centro situado en la Comunidad de Madrid',
                                'QUESTION': '¿El centro de estudios está situado en la Comunidad de Madrid?',
                                'VALUES': ['Sí', 'No'],
                                'HELPERS': None,
                                'TYPE': bool,
                                'HELP': ''},

             'IDIOMA_ESTUDIOS': {'NAME': 'Estudios bilingües',
                                 'QUESTION': '¿Los estudios son bilingües?',
                                 'VALUES': ['Sí', 'No'],
                                 'HELPERS': None,
                                 'TYPE': bool,
                                 'HELP': ''},

             'REPETIDOR': {'NAME': 'Repetidor',
                           'QUESTION': '¿Eres repetidor?',
                           'VALUES': ['Sí', 'No'],
                           'HELPERS': None,
                           'TYPE': bool,
                           'HELP': ''},

             'EDUCACION_ESPECIAL': {'NAME': 'Necesidades especiales',
                                    'QUESTION': '¿Tiene necesidades educativas especiales?',
                                    'VALUES': ['Sí', 'No'],
                                    'HELPERS': None,
                                    'TYPE': bool,
                                    'HELP': ''},

             'COTIZACION': {'NAME': 'Periodo mínimo',
                            'QUESTION': '¿Has cotizado el periodo mínimo?',
                            'VALUES': ['Sí', 'No'],
                            'HELPERS': None,
                            'TYPE': bool,
                            'HELP': ''},

             'PERIODO_MINIMO_ALTA': {'NAME': 'Periodo mínimo de cotización dado de alta',
                                     'QUESTION': 'Indica tu periodo mínimo de cotización dado de alta',
                                     'VALUES': ['Otros', '15 años o más', '1800 días o más', '500 días (periodo ininterrumpido durante 5 años)', '365 días (6 años inmediantamente anteriores)'],
                                     'HELPERS': None,
                                     'TYPE': list,
                                     'HELP': ''},

             'PERIODO_MINIMO_NO_ALTA': {'NAME': 'Periodo mínimo de cotización no dado de alta',
                                        'QUESTION': '¿Has cotizado más de 15 años aunque ahora no estés dado de alta?',
                                        'VALUES': ['Sí', 'No'],
                                        'HELPERS': None,
                                        'TYPE': list,
                                        'HELP': ''},

             'FALLECIMIENTO_CONYUGE': {'NAME': 'Fallecimiento por accidente del cónyuge',
                                       'QUESTION': '¿Ha fallecido por accidente el cónyuge?',
                                       'VALUES': ['Sí', 'No'],
                                       'HELPERS': None,
                                       'TYPE': list,
                                       'HELP': ''},

             'TEMORES': {'NAME': 'Temores fundados de persecución (*con la existencia de uno de ellos es suficente*)',
                         'QUESTION': 'Indica si hay temores fundados de persecución',
                         'VALUES': ['No', 'Raza', 'Religión', 'Nacionalidad', 'Opiniones Políticas', 'Pertenencia a un grupo social', 'Género', 'Orientación sexual'],
                         'HELPERS': None,
                         'TYPE': list,
                         'HELP': ''}
             }

AYUDAS = {1: {'ACTIVE': True,
              'NAME': 'RIM MADRID 2001',
              'TITLE': 'RENTA MÍNIMA DE INSERCIÓN COMUNIDAD DE MADRID',
              'LAW': 'Ley 15/2001, de 27 de diciembre, de renta mínima de inserción en la Comunidad de Madrid.',
              'DESCRIPTION': 'Renta mínima de inserción de la Comunidad de Madrid de 2001',
              'CONDITIONS': [[('RESIDENCIA', '=', 'Madrid')],
                             [('MADRID', '=', 'Sí')],
                             [('EDAD', '>=', 18)],
                             [('EMANCIPADO', '=', 'No')],
                             [('UNIDAD', '!=', 'No')],
                             [('VULNERABILIDAD_ECO', 'IN',
                               ['Sin renta', 'Sin ingresos', 'Sin patrimonio'])],
                             [('VULNERABILIDAD_ECO', 'NOT IN',
                               ['Paro', '<70% Salario Mínimo Anual'])],
                             [('MENORES', '=', 'Sí')],
                             [('SOLICITUD_PREVIA', '=', 'Sí')],
                             [('INSERCION', '=', 'Sí')],
                             [('VIOLENCIA', '=', 'No')],
                             [('TRATA', '=', 'No')],
                             [('EXPLOTACIOM', '=', 'No')]
                             ],
              'LAWURL': 'https://www.comunidad.madrid/servicios/asuntos-sociales/renta-minima-insercion',
              'REQUESTURL': 'http://www.madrid.org/cs/Satellite?c=CM_ConvocaPrestac_FA&cid=1109168955327&noMostrarML=true&pageid=1331802501637&pagename=PortalCiudadano/CM_ConvocaPrestac_FA/PCIU_fichaConvocaPrestac&vest=1331802501621'},
          2: {'ACTIVE': True,
              'NAME': 'RIM MADRID 2014',
              'TITLE': 'RENTA MÍNIMA DE INSERCIÓN COMUNIDAD DE MADRID',
              'LAW': 'Decreto 126/2014, de 20 de noviembre, del Consejo de Gobierno, por el que se aprueba el Reglamento de la Renta Mínima de Inserción en la Comunidad de Madrid.',
              'DESCRIPTION': 'Renta mínima de inserción de la Comunidad de Madrid de 2014',
              'CONDITIONS': [[('RESIDENCIA', '=', 'Madrid')],
                             [('MADRID', '=', 'Sí')],
                             [('EDAD', '>=', 18)],
                             [('EMANCIPADO', '=', 'No')],
                             [('UNIDAD', '!=', 'No')],
                             [('VULNERABILIDAD_ECO', 'IN',
                               ['Sin renta', 'Sin ingresos', 'Sin patrimonio'])],
                             [('VULNERABILIDAD_ECO', 'NOT IN',
                               ['Paro', '<70% Salario Mínimo Anual'])],
                             [('MENORES', '=', 'No')],
                             [('SOLICITUD_PREVIA', '=', 'Sí')],
                             [('INSERCION', '=', 'Sí')],
                             [('VIOLENCIA', '=', 'No')],
                             [('TRATA', '=', 'No')],
                             [('EXPLOTACIOM', '=', 'No')]
                             ]},
          3: {'ACTIVE': True,
              'NAME': 'RAI',
              'TITLE': 'RENTA ACTIVA INSERCIÓN',
              'LAW': 'Real Decreto 1369/2006, de 24 de noviembre, por el que se regula el programa de renta activa de inserción para desempleados con especiales necesidades económicas y '
                     'dificultad para encontrar empleo.',
              'DESCRIPTION': 'Renta mínima de inserción del Gobierno de España',
              'INCOMPATIBILITIES': 'Será incompatible con la percepción de cualquier prestación o subsidios por desempleo, o a la renta agraria. Así mismo, será incompatible cuando se perciba '
                                   'cualquier prestación o prestaciones, que le hagan superar el 75 por ciento del salario mínimo interprofesional, excluida la parte proporcional de dos pagas '
                                   'extraordinarias.',
              'CONDITIONS': [[('RESIDENCIA', 'IN', ['España', 'Madrid'])],
                             [('EDAD', '>=', 30)],
                             [('EDAD', '<', 65)],
                             [('EMANCIPADO', '=', 'No')],
                             [('VULNERABILIDAD_ECO', 'IN',
                               ['Sin renta', 'Sin ingresos'])],
                             [('VULNERABILIDAD_ECO', 'NOT IN',
                               ['Paro', '<70% Salario Mínimo Anual'])],
                             [('VIOLENCIA', '=', 'Sí'), ('MENORES', '=', 'Sí'), ('PARADOS_LARGA_DURACION', '=', 'Sí'), ('DISCAPACIDAD', '!=', 'No')],
                             [('SOLICITUD_PREVIA', '=', 'Sí')],
                             [('INSERCION', '=', 'No')],
                             [('TRATA', '=', 'No')],
                             [('EXPLOTACIOM', '=', 'No')]
                             ]},
          4: {'ACTIVE': True,
              'NAME': 'SANITARIA DISCAPACITADOS',
              'TITLE': 'ASISTENCIA SANITARIA Y PRESTACIÓN FARMACÉUTICA',
              'LAW': 'Real Decreto 383/1984, de 1 de febrero, por el que se establece y regula el sistema especial de prestaciones sociales y económicas previsto en la Ley 13/1982, '
                     'de 7 de abril, de integración social de los minusválidos.',
              'DESCRIPTION': 'Asistencia sanitaria a discapacitados',
              'CONDITIONS': [[('NACIONALIDAD', 'IN', ['Española', 'Comunitaria'])],
                             [('RESIDENCIA', 'IN', ['España', 'Madrid'])],
                             [('VULNERABILIDAD_ECO', 'IN',
                               ['Paro', '<70% Salario Mínimo Anual'])],
                             [('DISCAPACIDAD', '!=', 'No')],
                             [('RIESGOS', '=', 'No')]
                             ]},
          5: {'ACTIVE': True,
              'NAME': 'REHABILITACIÓN DISCAPACITADOS',
              'TITLE': 'REHABILITACIÓN MEDICO-FUNCIONAL',
              'LAW': 'Real Decreto 383/1984, de 1 de febrero, por el que se establece y regula el sistema especial de prestaciones sociales y económicas previsto en la Ley 13/1982, '
                     'de 7 de abril, de integración social de los minusválidos.',
              'DESCRIPTION': 'Rehabilitación médico-funcional para discapacitados',
              'INCOMPATIBILITIES': 'Ninguna, siempre y cuando los recursos personales del beneficiario no superen el límite máximo a que se refiere el artículo 32. A los efectos previstos en '
                                   'este artículo, se computarán como recursos personales los correspondientes al año natural anterior al del ',
              'CONDITIONS': [[('NACIONALIDAD', 'IN', ['Española', 'Comunitaria'])],
                             [('RESIDENCIA', 'IN', ['España', 'Madrid'])],
                             [('VULNERABILIDAD_ECO', 'IN',
                               ['Paro', '<70% Salario Mínimo Anual'])],
                             [('DISCAPACIDAD', '!=', 'No')],
                             [('RIESGOS', '=', 'Sí')]
                             ]},
          6: {'ACTIVE': True,
              'NAME': 'RECUPERACIÓN DISCAPACITADOS',
              'TITLE': 'RECUPERACIÓN PROFESIONAL',
              'LAW': 'Real Decreto 383/1984, de 1 de febrero, por el que se establece y regula el sistema especial de prestaciones sociales y económicas previsto en la Ley 13/1982, '
                     'de 7 de abril, de integración social de los minusválidos.',
              'DESCRIPTION': 'Recuperación profesional para discapacitados',
              'CONDITIONS': [[('NACIONALIDAD', 'IN', ['Española', 'Comunitaria'])],
                             [('RESIDENCIA', 'IN', ['España', 'Madrid'])],
                             [('EDAD', '>', 18)],
                             [('VULNERABILIDAD_ECO', 'IN',
                               ['Paro', '<70% Salario Mínimo Anual'])],
                             [('DISCAPACIDAD', '!=', 'No')],
                             [('RIESGOS', '=', 'Sí')],
                             [('RECUPERACION', '=', 'Sí')]
                             ]},
          7: {'ACTIVE': True,
              'NAME': 'INTEGRACIÓN DISCAPACITADOS',
              'TITLE': 'MEDIDAS DE INTEGRACIÓN SOCIAL',
              'LAW': 'Real Decreto 383/1984, de 1 de febrero, por el que se establece y regula el sistema especial de prestaciones sociales y económicas previsto en la Ley 13/1982, '
                     'de 7 de abril, de integración social de los minusválidos.',
              'DESCRIPTION': 'Medidas de integración social para discapacitados',
              'CONDITIONS': [[('NACIONALIDAD', 'IN', ['Española', 'Comunitaria'])],
                             [('RESIDENCIA', 'IN', ['España', 'Madrid'])],
                             [('VULNERABILIDAD_ECO', 'IN',
                               ['Paro', '<70% Salario Mínimo Anual'])],
                             [('DISCAPACIDAD', '!=', 'No')],
                             ]},
          8: {'ACTIVE': True,
              'NAME': 'SUBSIDIO GARANTÍA DISCAPACITADOS',
              'TITLE': 'SUBSIDIO DE GARANTÍA DE INGRESOS MÍNIMOS',
              'LAW': 'Real Decreto 383/1984, de 1 de febrero, por el que se establece y regula el sistema especial de prestaciones sociales y económicas previsto en la Ley 13/1982, '
                     'de 7 de abril, de integración social de los minusválidos.',
              'DESCRIPTION': 'Subsidio de garantiá de ingresos mínimos para discapacitados',
              'CONDITIONS': [[('NACIONALIDAD', 'IN', ['Española', 'Comunitaria'])],
                             [('RESIDENCIA', 'IN', ['España', 'Madrid'])],
                             [('EDAD', '>', 18)],
                             [('VULNERABILIDAD_ECO', 'IN',
                               ['Paro', '<70% Salario Mínimo Anual'])],
                             [('DISCAPACIDAD', '=', '>=85%')],
                             ]},
          9: {'ACTIVE': True,
              'NAME': 'SUBSIDIO AYUDA DISCAPACITADOS',
              'TITLE': 'SUBSIDIO POR AYUDA DE TERCERA PERSONA',
              'LAW': 'Real Decreto 383/1984, de 1 de febrero, por el que se establece y regula el sistema especial de prestaciones sociales y económicas previsto en la Ley 13/1982, '
                     'de 7 de abril, de integración social de los minusválidos.',
              'DESCRIPTION': 'Subsidio por ayuda de tercera persona para discapacitados',
              'CONDITIONS': [[('NACIONALIDAD', 'IN', ['Española', 'Comunitaria'])],
                             [('RESIDENCIA', 'IN', ['España', 'Madrid'])],
                             [('EDAD', '>', 18)],
                             [('VULNERABILIDAD_ECO', 'IN',
                               ['Paro', '<70% Salario Mínimo Anual'])],
                             [('DISCAPACIDAD', 'IN', ['>=75%', '>=85%'])],
                             ]},
          10: {'ACTIVE': True,
               'NAME': 'MOVILIDAD DISCAPACITADOS',
               'TITLE': 'SUBSIDIO DE MOVILIDAD Y COMPENSACIÓN POR GASTOS DE TRANSPORTE',
               'LAW': 'Real Decreto 383/1984, de 1 de febrero, por el que se establece y regula el sistema especial de prestaciones sociales y económicas previsto en la Ley 13/1982, '
                      'de 7 de abril, de integración social de los minusválidos.',
               'DESCRIPTION': 'Subsidio de movilidad y compensación por gastos de transporte para discapacitados',
               'CONDITIONS': [[('NACIONALIDAD', 'IN', ['Española', 'Comunitaria'])],
                              [('RESIDENCIA', 'IN', ['España', 'Madrid'])],
                              [('VULNERABILIDAD_ECO', 'IN',
                                ['Paro', '<70% Salario Mínimo Anual'])],
                              [('DISCAPACIDAD', '!=', 'No')],
                              ]},
          11: {'ACTIVE': True,
               'NAME': 'DEPENDENCIA',
               'TITLE': 'ATENCIÓN A PERSONAS EN DEPENDENCIA',
               'LAW': 'Ley 39/2006, de 14 de diciembre, de Promoción de la Autonomía Personal y Atención a las personas en situación de dependencia.',
               'DESCRIPTION': 'Ley de Dependencia del Gobierno de España',
               'CONDITIONS': [[('NACIONALIDAD', 'IN', ['Española', 'Comunitaria'])],
                              [('RESIDENCIA', 'IN', ['España', 'Madrid'])],
                              [('VULNERABILIDAD_ECO', '=', 'No')],
                              [('DISCAPACIDAD', '!=', 'No')],
                              [('SOLICITUD_PREVIA', '=', 'No')],
                              [('INSERCION', '=', 'Sí')],
                              ]},
          12: {'ACTIVE': True,
               'NAME': 'BECA FP',
               'TITLE': 'BECAS FORMACIÓN PROFESIONAL DE GRADO SUPERIOR',
               'LAW': 'Orden 1808/2020, de 31 de julio, del Consejero de Educación y Juventud, por la que se aprueba la convocatoria de becas de Formación Profesional de Grado Superior '
                      'correspondiente al curso 2020-2021',
               'DESCRIPTION': 'Becas de Formación Profesional de Grado Superior de la Comunidad de Madrid',
               'CONDITIONS': [[('VULNERABILIDAD_ECO', '=', 'Renta per cápita familiar <10.000')],
                              [('CURSANDO_ESTUDIOS', '=', 'Sí')],
                              [('ESTUDIOS', '=', 'Formación Profesional')],
                              [('MODALIDAD_ESTUDIOS', '=', 'Sí')],
                              [('CENTRO_ESTUDIOS', '=', 'Sí')],
                              [('LUGAR_ESTUDIOS', '=', 'Sí')],
                              [('IDIOMA_ESTUDIOS', '=', 'No')],
                              ]},
          13: {'ACTIVE': True,
               'NAME': 'ACCEDE',
               'TITLE': 'PROGRAMA ACCEDE',
               'LAW': 'ORDEN 3616/2019, de 5 de diciembre, del Consejero de Educación y Juventud, por la que se desarrolla el Decreto 168/2018, de 11 de diciembre, del Consejo de Gobierno, '
                      'por el que se aprueba el Reglamento del Programa Accede, sistema de préstamo de los libros',
               'DESCRIPTION': 'Sistema de préstamo de libros de la Comunidad de Madrid',
               'CONDITIONS': [[('ESTUDIOS', 'IN', ['Infantil', 'Primaria'])],
                              [('CURSANDO_ESTUDIOS', '=', 'Sí')],
                              [('MODALIDAD_ESTUDIOS', '=', 'Sí')],
                              [('LUGAR_ESTUDIOS', '=', 'Sí')],
                              [('IDIOMA_ESTUDIOS', '=', 'No')],
                              ]},
          14: {'ACTIVE': False,
               'NAME': 'BECA BACHILLER CAM 2019',
               'TITLE': 'BECAS PARA ESTUDIO DE BACHILLER EN LA COMUNIDAD DE MADRID',
               'LAW': 'Orden 1196/2019 de 11 de abril del Consejero de Educación e Investigación por la que se aprueba la convocatoria de becas para el estudio de bachillerato en la Comunidad de '
                      'Madrid, correspondiente al curso 2019/2020 (BOCM 95 de 23 de abril)',
               'DESCRIPTION': 'Becas para curso 2019/2020 de Bachiller de la Comunidad de Madrid',
               'CONDITIONS': [[('VULNERABILIDAD_ECO', '=', 'Renta per cápita familiar <10.000')],
                              [('CURSANDO_ESTUDIOS', '=', 'Sí')],
                              [('ESTUDIOS', 'IN', ['Infantil', 'Primaria', 'Secundaria', 'Bachiller'])],
                              [('MODALIDAD_ESTUDIOS', '=', 'Sí')],
                              [('CENTRO_ESTUDIOS', '=', 'Sí')],
                              [('LUGAR_ESTUDIOS', '=', 'Sí')],
                              [('IDIOMA_ESTUDIOS', '=', 'No')],
                              ]},
          15: {'ACTIVE': True,
               'NAME': 'BECA BACHILLER CAM 2020',
               'TITLE': 'BECAS PARA ESTUDIO DE BACHILLER EN LA COMUNIDAD DE MADRID',
               'LAW': 'Orden 373 / 2019 de la Consejería de Educación e Investigación, por la que se aprueban las bases reguladoras para la concesión de becas para el estudio de bachillerato en '
                      'la Comunidad de Madrid (BOCM 43 de 20 de febrero)',
               'DESCRIPTION': 'Becas para curso 2020/2021 de Bachiller de la Comunidad de Madrid',
               'CONDITIONS': [[('VULNERABILIDAD_ECO', '=', 'Renta per cápita familiar <10.000')],
                              [('CURSANDO_ESTUDIOS', '=', 'Sí')],
                              [('ESTUDIOS', 'IN', ['Infantil', 'Primaria', 'Secundaria', 'Bachiller'])],
                              [('CENTRO_ESTUDIOS', '=', 'Sí')],
                              [('LUGAR_ESTUDIOS', '=', 'Sí')],
                              [('IDIOMA_ESTUDIOS', '=', 'No')],
                              ]},
          16: {'ACTIVE': True,
               'NAME': 'BECA PERSONALIZADAS',
               'TITLE': 'BECAS AL ESTUDIO PERSONALIZADAS',
               'LAW': 'Real Decreto 1721/2007, de 21 de diciembre, por el que se establece el régimen de las becas y ayudas al estudio personalizadas',
               'DESCRIPTION': 'Becas de estudios del Gobierno de España',
               'CONDITIONS': [[('NACIONALIDAD', '!=', 'Española')],
                              [('RESIDENCIA', 'IN', ['España', 'Madrid'])],
                              [('CURSANDO_ESTUDIOS', '=', 'Sí')],
                              ]},
          17: {'ACTIVE': True,
               'NAME': 'BECA EDUC. INFANTIL',
               'TITLE': 'BECAS DE EDUCACIÓN INFANTIL',
               'LAW': 'ORDEN 349/2017, de 8 de febrero, de la Consejería de Educación, Juventud y Deporte y de la Consejería de Políticas Sociales y Familia, por la que se aprueban las bases '
                      'reguladoras para la concesión de becas para la escolarización en el primer ciclo de Educación ',
               'DESCRIPTION': 'Becas de Eduación Infantil de la Comunidad de Madrid',
               'INCOMPATIBILITIES': 'Las becas concedidas al amparo de las presentes bases reguladoras son incompatiblescon otras ayudas o becas con finalidad similar, provenientes de la propia '
                                    'Comunidad de Madrid, de otras Administraciones Públicas, de otros entes públicos o privados o de par-ticulares nacionales o internacionales.',
               'CONDITIONS': [[('CURSANDO_ESTUDIOS', '=', 'Sí')],
                              [('EDAD', '<=', 3), ('EDUCACION_ESPECIAL', '=', 'Sí')],
                              [('ESTUDIOS', '!=', 'Formación Profesional')],
                              [('CENTRO_ESTUDIOS', '=', 'Sí')],
                              [('LUGAR_ESTUDIOS', '=', 'Sí')],
                              ]},
          18: {'ACTIVE': True,
               'NAME': 'BECAS SEGUNDA OPORTUNIDAD',
               'TITLE': 'BECAS PARA EL ESTUDIO DE PROGRAMAS DE SEGUNDA OPORTUNIDAD',
               'LAW': 'Orden 2257/2018 de 11 de julio de la Consejería de Educación e Investigación, por la que se aprueban las bases reguladoras para la concesión de becas para el estudio de de '
                      'programas de segunda oportunidad (BOCM 168 de 16 de julio)',
               'DESCRIPTION': 'Becas para el estudio de programas de segunda oportunidad de la Comunidad de Madrid',
               'INCOMPATIBILITIES': '1. Las ayudas reguladas en las presentes normas reguladoras se declaran incompati-bles con otras ayudas o becas previstas con finalidad similar, '
                                    'provenientes de la propia Comunidad de Madrid, de otras Administraciones Públicas, de otros entes públicos o privadoso de particulares nacionales o '
                                    'internacionales.'
                                    '2. Se declaran compatibles estas ayudas con la utilización de rutas de transporte escolar, en aquellos casos en que la ayuda tenga como '
                                    'finalidad acercar al alumno a unaruta de transporte en funcionamiento.',
               'CONDITIONS': [[('EDAD', '<=', 30)],
                              [('CURSANDO_ESTUDIOS', '=', 'Sí')],
                              [('ESTUDIOS', '!=', 'Formación Profesional')],
                              [('CENTRO_ESTUDIOS', '=', 'Sí')],
                              [('IDIOMA_ESTUDIOS', '=', 'No')],
                              [('LUGAR_ESTUDIOS', '=', 'Sí')],
                              ]},
          19: {'ACTIVE': True,
               'NAME': 'TRANSPORTE ESCOLAR',
               'TITLE': 'AYUDAS PARA EL TRANSPORTE ESCOLAR',
               'LAW': 'Acuerdo de 27 de noviembre de 2018, del Consejo de Gobierno, por el que se aprueban las normas reguladoras del procedimiento de concesión directa de ayudas '
                      'individualizadas para el transporte escolar (BOCM nº 290, de 5 de diciembre)',
               'DESCRIPTION': 'Ayudas para el transporte escolar de la Comunidad de Madrid',
               'CONDITIONS': [[('ESTUDIOS', '!=', 'Formación Profesional')],
                              [('CURSANDO_ESTUDIOS', '=', 'Sí')],
                              [('CENTRO_ESTUDIOS', '=', 'Sí')],
                              [('MODALIDAD_ESTUDIOS', '=', 'Sí')],
                              [('IDIOMA_ESTUDIOS', '=', 'Sí')],
                              [('LUGAR_ESTUDIOS', '=', 'Sí')],
                              ]},
          20: {'ACTIVE': True,
               'NAME': 'BECAS SEGUNDA OPORTUNIDAD 2020',
               'TITLE': 'BECAS PARA EL ESTUDIO DE PROGRAMAS DE SEGUNDA OPORTUNIDAD',
               'LAW': 'Orden 2363 de 23 de septiembre de la Consejería de Educación y Juventud , por la que se aprueba la convocatoria de becas para el estudio de Programas de segunda '
                      'oportunidad , correspondiente al curso 2020/2021 (BOCM 236 de 29 de septiembre)',
               'DESCRIPTION': 'Becas para el estudio de programas de segunda oportunidad para el curso 2020/2021 de la Comunidad de Madrid',
               'CONDITIONS': [[('EDAD', '<=', 30)],
                              [('CURSANDO_ESTUDIOS', '=', 'Sí')],
                              [('ESTUDIOS', '!=', 'Formación Profesional')],
                              [('CENTRO_ESTUDIOS', '=', 'Sí')],
                              [('IDIOMA_ESTUDIOS', '=', 'No')],
                              [('LUGAR_ESTUDIOS', '=', 'Sí')],
                              ]},
          21: {'ACTIVE': True,
               'NAME': 'JUBILACION ORDINARIA',
               'TITLE': 'JUBILACIÓN ORDINARIA',
               'LAW': 'Real Decreto Legislativo 8/2015, de 30 de octubre, por el que se aprueba el texto refundido de la Ley General de la Seguridad Social',
               'DESCRIPTION': 'Jubilación Ordinaria',
               'CONDITIONS': [[('EDAD', '<=', 65)],
                              [('COTIZACION', '=', 'Sí')],
                              [('PERIODO_MINIMO_ALTA', '=', '15 años o más')],
                              ]},
          22: {'ACTIVE': True,
               'NAME': 'INCAPACIDAD PTE. TOTAL',
               'TITLE': 'PRESTACIÓN POR INCAPACIDAD PERMANENTE TOTAL',
               'LAW': 'Real Decreto Legislativo 8/2015, de 30 de octubre, por el que se aprueba el texto refundido de la Ley General de la Seguridad Social',
               'DESCRIPTION': 'Incapacidad Permanente Total',
               'CONDITIONS': [[('COTIZACION', '=', 'Sí')],
                              [('PERIODO_MINIMO_ALTA', '=', '1800 días o más')],
                              ]},
          23: {'ACTIVE': True,
               'NAME': 'INCAPACIDAD PTE. PARCIAL',
               'TITLE': 'PRESTACIÓN POR INCAPACIDAD PERMANENTE PARCIAL',
               'LAW': 'Real Decreto Legislativo 8/2015, de 30 de octubre, por el que se aprueba el texto refundido de la Ley General de la Seguridad Social',
               'DESCRIPTION': 'Incapacidad Permanente Parcial',
               'CONDITIONS': [[('COTIZACION', '=', 'Sí')],
                              [('PERIODO_MINIMO_ALTA', '=', '1800 días o más')],
                              ]},
          24: {'ACTIVE': True,
               'NAME': 'INCAPACIDAD PTE. ABSOLUTA',
               'TITLE': 'PRESTACIÓN POR INCAPACIDAD PERMANENTE ABSOLUTA',
               'LAW': 'Real Decreto Legislativo 8/2015, de 30 de octubre, por el que se aprueba el texto refundido de la Ley General de la Seguridad Social',
               'DESCRIPTION': 'Incapacidad Permanente Absoluta',
               'CONDITIONS': [[('EDAD', '>', 65)],
                              [('COTIZACION', '=', 'Sí')],
                              [('PERIODO_MINIMO_ALTA', '=', '1800 días o más'), ('PERIODO_MINIMO_NO_ALTA', '=', 'Sí')],
                              ]},
          25: {'ACTIVE': True,
               'NAME': 'GRAN INVALIDEZ',
               'TITLE': 'PRESTACIÓN POR GRAN INVALIDEZ',
               'LAW': 'Real Decreto Legislativo 8/2015, de 30 de octubre, por el que se aprueba el texto refundido de la Ley General de la Seguridad Social',
               'DESCRIPTION': 'Gran Invalidez',
               'CONDITIONS': [[('EDAD', '>', 65)],
                              [('COTIZACION', '=', 'Sí')],
                              [('PERIODO_MINIMO_ALTA', '=', '1800 días o más'), ('PERIODO_MINIMO_NO_ALTA', '=', 'Sí')],
                              ]},
          26: {'ACTIVE': True,
               'NAME': 'VIUDEDAD',
               'TITLE': 'PENSIÓN DE VIUEDAD',
               'LAW': 'Real Decreto Legislativo 8/2015, de 30 de octubre, por el que se aprueba el texto refundido de la Ley General de la Seguridad Social',
               'DESCRIPTION': 'Viudedad',
               'CONDITIONS': [[('COTIZACION', '=', 'Sí'), ('FALLECIMIENTO_CONYUGE', '=', 'Sí')],
                              [('PERIODO_MINIMO_ALTA', '=', '500 días (periodo ininterrumpido durante 5 años)'), ('PERIODO_MINIMO_NO_ALTA', '=', 'Sí')],
                              ]},
          27: {'ACTIVE': True,
               'NAME': 'ORFANDAD',
               'TITLE': 'PENSIÓN DE ORFANDAD',
               'LAW': 'Real Decreto Legislativo 8/2015, de 30 de octubre, por el que se aprueba el texto refundido de la Ley General de la Seguridad Social',
               'DESCRIPTION': 'Orfandad',
               'CONDITIONS': [[('EDAD', '>', 21)],
                              [('COTIZACION', '=', 'Sí')],
                              [('PERIODO_MINIMO_ALTA', '=', '500 días (periodo ininterrumpido durante 5 años)'), ('PERIODO_MINIMO_NO_ALTA', '=', 'Sí')],
                              ]},
          28: {'ACTIVE': True,
               'NAME': 'DESEMPLEO',
               'TITLE': 'PRESTACIÓN POR DESEMPLEO',
               'LAW': 'Real Decreto Legislativo 8/2015, de 30 de octubre, por el que se aprueba el texto refundido de la Ley General de la Seguridad Social',
               'DESCRIPTION': 'Desempleo',
               'CONDITIONS': [[('EDAD', '>', 65)],
                              [('COTIZACION', '=', 'Sí')],
                              [('PERIODO_MINIMO_ALTA', '=', '365 días (6 años inmediantamente anteriores)')],
                              ]},
          29: {'ACTIVE': True,
               'NAME': 'INTEGRACIÓN EXTRANJEROS 2000',
               'TITLE': 'DERECHOS Y LIBERTADES EXTRANJEROS',
               'LAW': 'LO 4/2000, de 11 de enero,  sobre derechos y libertades  de los extranjeros en España y su integración social.',
               'DESCRIPTION': 'Integración social de extranjeros del Gobierno de España',
               'CONDITIONS': [[('NACIONALIDAD', '!=', 'Española')],
                              ]},
          30: {'ACTIVE': True,
               'NAME': 'INTEGRACIÓN EXTRANJEROS 2011',
               'TITLE': 'DERECHOS Y LIBERTADES EXTRANJEROS',
               'LAW': 'Real Decreto 557/2011, de 20 de abril, por el que se aprueba el Reglamento de la LO 4/2000, sobre derechos y libertades de los extranjeros en España y su integración '
                      'social, tras su reforma por la LO 2/2009.',
               'DESCRIPTION': 'Integración social de extranjeros del Gobierno de España',
               'CONDITIONS': [[('NACIONALIDAD', '!=', 'Española')],
                              ]},
          31: {'ACTIVE': True,
               'NAME': 'ASILO',
               'TITLE': 'ASILO 2009',
               'LAW': 'Ley 12/2009, de 30 de octubre, reguladora del derecho de asilo y la protección subsidiaria.',
               'DESCRIPTION': 'Derecho de asilo y protección',
               'CONDITIONS': [[('NACIONALIDAD', 'NOT IN', ['Española', 'Comunitaria'])],
                              [('TEMORES', '!=', 'No')],
                              ]},
          32: {'ACTIVE': True,
               'NAME': 'ASILO 1995',
               'TITLE': 'ASILO',
               'LAW': 'Real Decreto 203/1995, de 10 de febrero, por el que se aprueba el Reglamento de aplicación de la Ley 571984, de 26 de marzo, reguladora del derecho de asilo y de la '
                      'condición de refugiado, modificada por la Ley 9/1994, de 19 de mayo.',
               'DESCRIPTION': 'Derecho de asilo y refugiados',
               'CONDITIONS': [[('NACIONALIDAD', 'NOT IN', ['Española', 'Comunitaria'])],
                              [('TEMORES', '!=', 'No')],
                              ]},
          33: {'ACTIVE': True,
               'NAME': 'LIBRE CIRCUILACIÓN UE',
               'TITLE': 'LIBRE CIRCULACION UNION EUROPEA',
               'LAW': 'Real Decreto 240/2007, de 16 de febrero, sobre entrada, libre circulación, y residencia en España de los ciudadanos de los Estados miembros de la Unión Europea y de otros '
                      'Estados parte en el Acuerdo sobre el Espacio Económico Europeo.',
               'DESCRIPTION': 'Libre circulación de ciudadanos europeos',
               'CONDITIONS': [[('NACIONALIDAD', '=', 'Comunitaria')],
                              [('UNIDAD', 'IN', ['Unión matrimonial', 'Unión de hecho', 'Consanguiniedad (hasta 4º grado)', 'Discapacitados a su cargo'])],
                              ]},
          34: {'ACTIVE': True,
               'NAME': 'IMV',
               'TITLE': 'INGRESO MÍNIMO VITAL',
               'LAW': 'Real Decreto-Ley 20/2020, de 29 de mayo, por el que se establece el ingreso mínimo vital.',
               'DESCRIPTION': 'Ingreso Mínimo Vital del Gobierno de España',
               'INCOMPATIBILITIES': 'La Prestación del Ingreso Mínimo Vital es incompatible con cualquier otra ayuda económica que se esté percibiendo de forma simultánea con ésta. Así mismo, '
                                    'es obligatorio, haber solicitado las pensiones y prestaciones públicas vigentes que se determinen reglamentariamente, a las que pudieran tener derecho. En '
                                    'todo caso, quedan exceptuados los salarios sociales, rentas mínimas de inserción o ayudas análogas de asistencia social concedidas por las comunidades '
                                    'autónomas. La percepción de la prestación de ingreso mínimo vital será incompatible con la percepción de la asignación económica por hijo o menor a cargo, '
                                    'sin discapacidad o con discapacidad inferior al 33 por ciento, cuando exista identidad de causantes o beneficiarios de esta. En el supuesto de que la cuantía '
                                    'de la prestación de ingreso mínimo vital sea superior a la de la asignación económica por hijo o menor a cargo referida en el párrafo anterior, '
                                    'se reconocerá el derecho a la prestación de ingreso mínimo vital. Dicho reconocimiento extinguirá el derecho a la asignación por hijo o menor a cargo. En el '
                                    'supuesto de que la cuantía de la prestación de ingreso mínimo vital sea inferior a la de la asignación económica por hijo o menor a cargo, '
                                    'y el interesado optara por la primera, su reconocimiento extinguirá el derecho a la asignación económica por hijo o menor a cargo. Si optara por la '
                                    'asignación económica por hijo o menor a cargo, se denegará por esta causa la solicitud de la prestación de ingreso mínimo vital.',
               'CONDITIONS': [[('RESIDENCIA', 'IN', ['España', 'Madrid'])],
                              [('EDAD', '>=', 18), ('EMANCIPADO', '=', 'Sí')],
                              [('UNIDAD', '!=', 'No')],
                              [('VULNERABILIDAD_ECO', 'IN', ['Sin renta', 'Sin ingresos', 'Sin patrimonio'])],
                              [('SOLICITUD_PREVIA', '=', 'Sí')],
                              ],
               'LAWURL': 'https://www.boe.es/buscar/pdf/2020/BOE-A-2020-5493-consolidado.pdf',
               'REQUESTURL': 'https://imv.seg-social.es/'},
          }
